import { defineSchema, defineTable } from 'convex/server';
import { v } from 'convex/values';

export default defineSchema({
  seasons: defineTable({
    id: v.string(),
    name: v.string(),
    startDate: v.string(),
    endDate: v.string(),
    active: v.boolean(),
  }),

  teams: defineTable({
    id: v.string(),
    name: v.string(),
    category: v.string(),
    coachId: v.string(),
    seasonId: v.string(),
    color: v.string(),
  }).index('by_string_id', ['id']),

  players: defineTable({
    id: v.string(),
    firstName: v.string(),
    lastName: v.string(),
    dateOfBirth: v.string(),
    primaryTeamId: v.string(),
    secondaryTeamId: v.optional(v.string()),
    preferredPosition: v.string(),
    appetences: v.record(v.string(), v.number()),
    number: v.optional(v.number()),
    active: v.boolean(),
  }).index('by_string_id', ['id']),

  contacts: defineTable({
    id: v.string(),
    firstName: v.string(),
    lastName: v.string(),
    phone: v.string(),
    email: v.string(),
    type: v.string(),
    playerIds: v.array(v.string()),
    userId: v.optional(v.string()),
    consentDate: v.optional(v.string()),
  }),

  users: defineTable({
    id: v.string(),
    email: v.string(),
    firstName: v.string(),
    lastName: v.string(),
    roles: v.array(v.string()),
    teamIds: v.array(v.string()),
    contactId: v.optional(v.string()),
  }),

  matches: defineTable({
    id: v.string(),
    teamId: v.string(),
    seasonId: v.string(),
    tournamentId: v.optional(v.string()),
    date: v.string(),
    time: v.string(),
    location: v.string(),
    address: v.string(),
    isHome: v.boolean(),
    opponent: v.string(),
    status: v.string(),
    phase: v.string(),
    scoreHome: v.optional(v.number()),
    scoreAway: v.optional(v.number()),
    note: v.optional(v.string()),
    liveActive: v.boolean(),
    meetingAddress: v.optional(v.string()),
    meetingTime: v.optional(v.string()),
    meetingNote: v.optional(v.string()),
  }).index('by_string_id', ['id']),

  matchEvents: defineTable({
    id: v.string(),
    matchId: v.string(),
    type: v.string(),
    minute: v.optional(v.number()),
    playerId: v.optional(v.string()),
    player2Id: v.optional(v.string()),
    note: v.optional(v.string()),
  }).index('by_match', ['matchId']),

  trainings: defineTable({
    id: v.string(),
    teamId: v.string(),
    date: v.string(),
    time: v.string(),
    duration: v.number(),
    type: v.string(),
    cancelled: v.boolean(),
    theme: v.optional(v.string()),
    note: v.optional(v.string()),
    seriesId: v.optional(v.string()),
  }).index('by_string_id', ['id']),

  trainingBlocks: defineTable({
    id: v.string(),
    trainingId: v.string(),
    order: v.number(),
    duration: v.number(),
    title: v.string(),
    description: v.optional(v.string()),
    exerciseId: v.optional(v.string()),
  }),

  exercises: defineTable({
    id: v.string(),
    title: v.string(),
    description: v.optional(v.string()),
    category: v.string(),
    suggestedDuration: v.optional(v.number()),
    tags: v.array(v.string()),
  }),

  attendances: defineTable({
    id: v.string(),
    sessionType: v.union(v.literal('match'), v.literal('training')),
    sessionId: v.string(),
    playerId: v.string(),
    status: v.string(),
    note: v.optional(v.string()),
    recordedBy: v.optional(v.string()),
  }).index('by_session', ['sessionType', 'sessionId']),

  lineups: defineTable({
    id: v.string(),
    teamId: v.string(),
    matchId: v.optional(v.string()),
    name: v.string(),
    formation: v.string(),
    slots: v.array(
      v.object({
        position: v.string(),
        playerId: v.optional(v.string()),
        x: v.number(),
        y: v.number(),
      })
    ),
    substituteIds: v.array(v.string()),
    createdAt: v.string(),
  }).index('by_string_id', ['id']),

  positionHistory: defineTable({
    id: v.string(),
    playerId: v.string(),
    matchId: v.string(),
    matchDate: v.string(),
    opponent: v.string(),
    period: v.string(),
    position: v.string(),
  }).index('by_player', ['playerId']),

  tournaments: defineTable({
    id: v.string(),
    seasonId: v.string(),
    name: v.string(),
    dateStart: v.string(),
    dateEnd: v.optional(v.string()),
    location: v.string(),
    address: v.optional(v.string()),
    organizer: v.string(),
    isOrganizedByClub: v.boolean(),
    teamIds: v.array(v.string()),
    format: v.string(),
    status: v.string(),
  }),

  tournamentGroups: defineTable({
    id: v.string(),
    tournamentId: v.string(),
    name: v.string(),
    type: v.union(v.literal('poule'), v.literal('elimination')),
    order: v.number(),
  }),

  carpoolOffers: defineTable({
    id: v.string(),
    matchId: v.string(),
    offeredBy: v.string(),
    seats: v.number(),
    departureLocation: v.optional(v.string()),
    departureTime: v.optional(v.string()),
    playerIds: v.array(v.string()),
    note: v.optional(v.string()),
  }),

  surveys: defineTable({
    id: v.string(),
    teamId: v.string(),
    sessionType: v.string(),
    sessionId: v.optional(v.string()),
    question: v.string(),
    deadline: v.string(),
    status: v.string(),
    sendNotification: v.boolean(),
    createdBy: v.string(),
  }).index('by_string_id', ['id']),

  surveyResponses: defineTable({
    id: v.string(),
    surveyId: v.string(),
    playerId: v.string(),
    intentionJoueur: v.optional(v.string()),
    dateIntentionJoueur: v.optional(v.string()),
    confirmationParent: v.optional(v.string()),
    dateConfirmationParent: v.optional(v.string()),
    parentUserId: v.optional(v.string()),
    note: v.optional(v.string()),
  }).index('by_survey', ['surveyId']),

  notifications: defineTable({
    id: v.string(),
    userId: v.string(),
    type: v.string(),
    message: v.string(),
    read: v.boolean(),
    relatedId: v.optional(v.string()),
    relatedType: v.optional(v.string()),
    createdAt: v.string(),
  }),

  unavailabilities: defineTable({
    id: v.string(),
    playerId: v.string(),
    startDate: v.string(),
    endDate: v.optional(v.string()),
    motif: v.string(),
    declaredBy: v.string(),
    note: v.optional(v.string()),
    injuryId: v.optional(v.string()),
  }).index('by_player', ['playerId']),

  injuries: defineTable({
    id: v.string(),
    playerId: v.string(),
    zone: v.string(),
    nature: v.string(),
    startDate: v.string(),
    estimatedReturnDate: v.optional(v.string()),
    actualReturnDate: v.optional(v.string()),
    status: v.string(),
    noteCoach: v.optional(v.string()),
  }).index('by_player', ['playerId']),
});
